package com.confApi.chatconfianca.hotel;
import com.confApi.chatconfianca.v2.*;
import com.confApi.chatgpt.dto.*;
import com.confApi.chatgpt.service.ChatService;
import com.confApi.chatgpt.tools.ToolRouter;
import com.confApi.chatconfianca.intencao.ChatConfiancaDecisaoIa;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import org.mockito.ArgumentCaptor;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.*;
import com.confApi.chatconfianca.hotel.ChatIaHotelListaDocumento.*;

class ChatIaHotelListaServiceTest {
    ChatIaHotelListaClient client=mock(ChatIaHotelListaClient.class);
    ChatIaHotelReservaService reserva=mock(ChatIaHotelReservaService.class);
    Clock clock=Clock.fixed(Instant.parse("2026-09-14T12:00:00Z"),ZoneId.of("America/Cuiaba"));
    ChatIaHotelListaService service=new ChatIaHotelListaService(client,reserva,true,clock);
    ConversationRequestDTO session=new ConversationRequestDTO("confia","CGB","ERP",10L,20L,"Liste minhas reservas de hotel",List.of(),null,false,List.of());
    ChatIaHotelDocumento.Configuracao config=ChatIaHotelServiceTest.config();
    @BeforeEach void setup()throws Exception{when(client.configuracao()).thenReturn(config);}
    ChatV2Plan p(){var p=ChatV2Plan.of(ChatV2Capability.HOTEL_LISTA);p.setAgencia(10);p.setUsuario(20);return p;}
    Item item(int id,String data){var r=new Item();r.setId(id);r.setAgencia(10);r.setHotel("Hotel Teste");r.setCidade("Recife");r.setLocalizador("H"+id);r.setCriacao(data);r.setEntrada("2026-09-20");r.setSaida("2026-09-23");r.setDataOrdenacao(data);return r;}
    ChatIaHotelListaDocumento doc(boolean mais,Item... items){var d=new ChatIaHotelListaDocumento();d.setConfiguracao(config);d.setConsultadoEm("2026-09-14T12:00:00Z");d.setReservas(List.of(items));d.setMaisResultados(mais);if(mais){d.setProximaData(items[items.length-1].getDataOrdenacao());d.setProximoId(items[items.length-1].getId());}return d;}
    void paginaUm(ChatV2Plan p)throws Exception{when(client.consultar(any(),anyInt())).thenReturn(doc(true,item(72,"2026-09-13 10:00:00"),item(71,"2026-09-13 10:00:00")));assertEquals("DADOS_CONSULTADOS",service.listarReservas(p,session).status());}
    @Test void desligadoNaoChamaNada(){assertEquals("CAPACIDADE_INDISPONIVEL",new ChatIaHotelListaService(client,reserva,false,clock).listarReservas(p(),session).status());verifyNoInteractions(client,reserva);}
    @Test void outraAgenciaOuUsuarioNaoConsulta(){var p=p();p.setAgencia(11);assertEquals("CONSULTA_BLOQUEADA",service.listarReservas(p,session).status());p.setAgencia(10);p.setUsuario(21);assertEquals("CONSULTA_BLOQUEADA",service.listarReservas(p,session).status());verifyNoInteractions(client);}
    @Test void configuracaoInativaBloqueia()throws Exception{when(client.configuracao()).thenReturn(null);assertEquals("CONSULTA_BLOQUEADA",service.listarReservas(p(),session).status());verify(client,never()).consultar(any(),anyInt());}
    @Test void semPeriodoAplica30DiasCriacaoEInforma()throws Exception{when(client.consultar(any(),anyInt())).thenReturn(doc(false,item(1,"2026-09-10 10:00:00")));var p=p();var out=service.listarReservas(p,session);assertEquals("DADOS_CONSULTADOS",out.status());var c=ArgumentCaptor.forClass(Consulta.class);verify(client).consultar(c.capture(),eq(8));assertEquals(10,c.getValue().getAgencia());assertEquals("CRIACAO",c.getValue().getTipoData());assertEquals("2026-08-16",c.getValue().getInicio());assertEquals("2026-09-14",c.getValue().getFim());assertTrue(out.texto().contains("16/08/2026"));assertEquals(1,p.getListaHotelEstado().getPagina());verifyNoInteractions(reserva);}
    @Test void entradaNaoViraCriacaoEOrdenaCrescente()throws Exception{var p=p();p.getParametros().putAll(Map.of("listaHotelTipoData","ENTRADA","listaHotelInicio","2026-09-01","listaHotelFim","2026-09-30"));when(client.consultar(any(),anyInt())).thenReturn(doc(false,item(1,"2026-09-20 00:00:00"),item(2,"2026-09-20 00:00:00")));assertEquals("DADOS_CONSULTADOS",service.listarReservas(p,session).status());var c=ArgumentCaptor.forClass(Consulta.class);verify(client).consultar(c.capture(),eq(8));assertEquals("ENTRADA",c.getValue().getTipoData());}
    @Test void periodoAmbiguoIncompletoInvalidoOuLongoPedeEsclarecimento()throws Exception{for(var params:List.of(Map.of("listaHotelInicio","2026-09-01","listaHotelFim","2026-09-30"),Map.of("listaHotelTipoData","ENTRADA"),Map.of("listaHotelTipoData","SAIDA","listaHotelInicio","2026-02-30","listaHotelFim","2026-03-01"),Map.of("listaHotelTipoData","CRIACAO","listaHotelInicio","2025-01-01","listaHotelFim","2026-09-14"))){var p=p();p.getParametros().putAll(params);assertEquals("AGUARDANDO_DADOS",service.listarReservas(p,session).status());}verify(client,never()).consultar(any(),anyInt());}
    @Test void outraAgenciaNoRetornoNuncaExibida()throws Exception{var i=item(1,"2026-09-10 10:00:00");i.setAgencia(11);when(client.consultar(any(),anyInt())).thenReturn(doc(false,i));var out=service.listarReservas(p(),session);assertEquals("ERRO_INTEGRACAO",out.status());assertFalse(out.texto().contains("Hotel Teste"));}
    @Test void maisUsaCursorServidorEFiltrosDaMesmaPagina()throws Exception{var p=p();paginaUm(p);clearInvocations(client);p.getParametros().put("listaHotelComando","MAIS");when(client.consultar(any(),anyInt())).thenReturn(doc(false,item(70,"2026-09-12 10:00:00")));assertEquals("DADOS_CONSULTADOS",service.listarReservas(p,session).status());var c=ArgumentCaptor.forClass(Consulta.class);verify(client).consultar(c.capture(),eq(8));assertEquals(71,c.getValue().getAposId());assertEquals("2026-09-13 10:00:00",c.getValue().getAposData());assertEquals(2,p.getListaHotelEstado().getPagina());assertEquals(Map.of("1",70),p.getListaHotelEstado().getOpcoes());}
    @Test void fimDaListaNaoFazOutraConsulta()throws Exception{var p=p();when(client.consultar(any(),anyInt())).thenReturn(doc(false,item(1,"2026-09-10 10:00:00")));service.listarReservas(p,session);clearInvocations(client);p.getParametros().put("listaHotelComando","MAIS");assertEquals("SEM_RESULTADO",service.listarReservas(p,session).status());verify(client,never()).consultar(any(),anyInt());}
    @Test void abrirSoNumeroDaUltimaPagina()throws Exception{var p=p();paginaUm(p);clearInvocations(client);when(reserva.consultarDaLista(p,session,71)).thenReturn(new ChatIaHotelReservaService.Resultado("DADOS_CONSULTADOS","Detalhes autorizados"));p.getParametros().putAll(Map.of("listaHotelComando","ABRIR","listaHotelOpcao","2"));assertEquals("Detalhes autorizados",service.listarReservas(p,session).texto());verify(reserva).consultarDaLista(p,session,71);verify(client,never()).consultar(any(),anyInt());}
    @Test void numeroInexistenteNaoConsultaDetalhes()throws Exception{var p=p();paginaUm(p);p.getParametros().putAll(Map.of("listaHotelComando","ABRIR","listaHotelOpcao","5"));assertEquals("AGUARDANDO_DADOS",service.listarReservas(p,session).status());verifyNoInteractions(reserva);}
    @Test void cursorAusenteOuFiltrosAlteradosNaoAvancam()throws Exception{var p=p();p.getParametros().put("listaHotelComando","MAIS");assertEquals("AGUARDANDO_DADOS",service.listarReservas(p,session).status());paginaUm(p);clearInvocations(client);p.getParametros().putAll(Map.of("listaHotelComando","MAIS","listaHotelCidade","Outra cidade"));assertEquals("AGUARDANDO_DADOS",service.listarReservas(p,session).status());verify(client,never()).consultar(any(),anyInt());}
    @Test void reiniciarListaNaoUsaCursorVelho()throws Exception{var p=p();paginaUm(p);clearInvocations(client);p.getParametros().putAll(Map.of("listaHotelComando","LISTAR","listaHotelCidade","Recife"));service.listarReservas(p,session);var c=ArgumentCaptor.forClass(Consulta.class);verify(client).consultar(c.capture(),eq(8));assertNull(c.getValue().getAposId());assertEquals(1,p.getListaHotelEstado().getPagina());}
    @Test void revisaoMudouInvalidaEscolha()throws Exception{var p=p();paginaUm(p);var c=ChatIaHotelServiceTest.config();c.setRevisao("outra");when(client.configuracao()).thenReturn(c);p.getParametros().putAll(Map.of("listaHotelComando","ABRIR","listaHotelOpcao","1"));assertEquals("AGUARDANDO_DADOS",service.listarReservas(p,session).status());verifyNoInteractions(reserva);}
    @Test void cursorRepetidoDuplicatasOuOrdemErradaFalham()throws Exception{for(var d:List.of(doc(false,item(1,"2026-09-10 10:00:00"),item(1,"2026-09-10 10:00:00")),doc(false,item(1,"2026-09-10 10:00:00"),item(2,"2026-09-11 10:00:00")))){when(client.consultar(any(),anyInt())).thenReturn(d);assertEquals("ERRO_INTEGRACAO",service.listarReservas(p(),session).status());}var p=p();paginaUm(p);p.getParametros().put("listaHotelComando","MAIS");assertEquals("ERRO_INTEGRACAO",service.listarReservas(p,session).status());}
    @Test void dataMalformadaDoManagerEErroDeIntegracaoNaoErroDoUsuario()throws Exception{var i=item(1,"data-invalida");when(client.consultar(any(),anyInt())).thenReturn(doc(false,i));assertEquals("ERRO_INTEGRACAO",service.listarReservas(p(),session).status());}
    @Test void cursorDivergenteDaUltimaLinhaFalha()throws Exception{var d=doc(true,item(71,"2026-09-10 10:00:00"));d.setProximoId(999);when(client.consultar(any(),anyInt())).thenReturn(d);assertEquals("ERRO_INTEGRACAO",service.listarReservas(p(),session).status());}
    @Test void vazioNaoPrometeAusenciaNoFornecedor()throws Exception{when(client.consultar(any(),anyInt())).thenReturn(doc(false));var r=service.listarReservas(p(),session);assertEquals("SEM_RESULTADO",r.status());assertTrue(r.texto().contains("não sincronizadas"));}
    @Test void erroNaoVazaCausaENaoUsaFallback()throws Exception{when(client.consultar(any(),anyInt())).thenThrow(new java.io.IOException("segredo"));var r=service.listarReservas(p(),session);assertEquals("ERRO_INTEGRACAO",r.status());assertFalse(r.texto().contains("segredo"));verifyNoInteractions(reserva);}
    @Test void executorNaoChamaAereoNemModelo()throws Exception{var chat=mock(ChatService.class);var tools=mock(ToolRouter.class);when(client.consultar(any(),anyInt())).thenReturn(doc(false,item(1,"2026-09-10 10:00:00")));var p=p();p.getParametros().put("localizador","FLSEMF");new ChatV2Executor(chat,tools,new ObjectMapper(),null,reserva,service).executar(p,session,new ChatConfiancaDecisaoIa());assertEquals("DADOS_CONSULTADOS",p.getResultado());assertFalse(p.getParametros().containsKey("localizador"));verifyNoInteractions(chat,tools);}
}
